name             'bks-postgresql'
maintainer       'Ron Ellis'
maintainer_email 'rone@benetech.org'
license          'All rights reserved'
description      'Installs/Configures postgresql'
long_description 'Installs/Configures postgresql'
version          '0.1.36'

depends 'aws', '~> 2.4.0'
depends 'sysctl', '~> 0.6.0'
depends 'database', '~> 4.0.6'
depends 'bookshare'