name             'bks-postgresql'
maintainer       'Ron Ellis'
maintainer_email 'rone@benetech.org'
license          'All rights reserved'
description      'Installs/Configures postgresql'
long_description 'Installs/Configures postgresql'
version          '0.1.9'